// src/App.vue
<template>
  <div id="app">
    <Nav :progress="progress" @setLevel="onSetLevel"/>
    <div class="container">
      <component :is="currentComponent" :progress="progress" @onIntroNext="onIntroNext" @onProblemNext="onProblemNext"/>
    </div>
  </div>
</template>

<script>
import Nav from './components/Nav.vue'
import Intro from './components/Intro.vue'
import Problem from './components/Problem.vue'
import Summary from './components/Summary.vue'
import problemGenerator from './components/problem_generator.js'

export default {
  name: 'App',
  components: {
    Nav,
    Intro,
    Problem,
    Summary
  },
  data() {
    return {
      showIntro: true,
      showQuestion: false,
      showSummary: false,
      currentComponent: Intro,
      progress: {
        right: 0,
        wrong: 0,
        wrong_questions: [],
        begin: null,
        end: null,
        total: 30,
        level: 0,
        level_desc: "",
      },
    }

  },
  methods: {
    reset(){
      Object.assign(this.$data, this.$options.data());
    },
    onIntroNext () {
      this.currentComponent = Problem;
      this.progress.begin = new Date();
    },
    onProblemNext () {
      this.currentComponent = Summary;
      this.progress.end = new Date();
    },
    onSetLevel(level){
      this.reset();
      switch(level){
        case 1:
          this.progress.level = 1;
          this.progress.level_desc = "Minus under 20";
          this.progress.total = 30;
          Problem.methods.generateQuestion = problemGenerator.problem_generator_1;
          break;
        case 2:
          this.progress.level = 2;
          this.progress.level_desc = "Minus under 100";
          this.progress.total = 30;
          Problem.methods.generateQuestion = problemGenerator.problem_generator_2;
          break;
        case 3:
          this.progress.level = 3;
          this.progress.level_desc = "Minus under 100 with borrow";
          this.progress.total = 10;
          Problem.methods.generateQuestion = problemGenerator.problem_generator_3;
          break;
        case 4:
          this.progress.level = 4;
          this.progress.level_desc = "Minus under 100 with borrow mixed";
          this.progress.total = 10;
          Problem.methods.generateQuestion = problemGenerator.problem_generator_4;
          break;
      }
    },
  },
  mounted(){
    this.onSetLevel(1);
  }
}
</script>

<style>
.container {
  padding-top: 70px;
}
</style>

// src/components/app.jsx
import React, { useState, useEffect, useReducer } from 'react';
import NavBar from './navbar';
import Intro from './intro';
import Problem from './problem';
import Summary from './summary';


const App = () => {
  const [levels] = useState([
    {id: 1, title: "Level 1", desc: "Minus under 20", total: 30},
    {id: 2, title: "Level 2", desc: "Minus under 100", total: 30},
    {id: 3, title: "Level 3", desc: "Minus under 100 with borrow", total: 10},
    {id: 4, title: "Level 4", desc: "Minus under 100 with borrow mixed", total: 10},
    ]);

  const initShared = {
    level: levels[0],
    right: 0,
    wrong: 0,
    end: null,
    begin: null,
    wrong_questions: []
  };

  const [shared, dispathShared] = useReducer((state, action)=>{
    switch (action.type) {
      case 'setLevel':
        return {...initShared, level:action.level}
      case 'begin':
        return {...state, begin: Date.now()};
      case 'end':
        return {...state, end: Date.now()};
      case 'answer':
        if(action.isRight)
          return {...state, right: state.right+1};
        else
          return {...state, wrong: state.wrong+1, wrong_questions: state.wrong_questions.concat(action.wrong)};
      default:
        throw new Error(action.type + "has not found");
    }
  }, initShared);
    
  useEffect(()=>{
    if(shared.right+shared.wrong>=shared.level.total){
      dispathShared({type: 'end'});
    }
  },[shared.right, shared.wrong, shared.level.total]);

  const onSetLevel = (i) => {
    dispathShared({type: 'setLevel', level: i});
  }

  return (
    <div className="App">
      <NavBar shared={shared} levels={levels} onSetLevel={onSetLevel}/>
      <div className="container">
        {(shared.begin==null) && 
          <Intro shared={shared} levels={levels} onStart={()=>dispathShared({type: 'begin'})}/>
        }

        {(shared.begin && shared.end == null) && <Problem shared={shared} onAnswer={(isRight, wrong)=> dispathShared({type:'answer', isRight: isRight, wrong: wrong})} /> }

        {(shared.end) && <Summary shared={shared} levels={levels} />}
      </div>
    </div>
  );
}

export default App;
