// src/components/Intro.vue
<template>
  <div class="jumbotron">
    <h1>Minus Level {{ progress.level }}</h1>
    <p>{{ progress.level_desc }}</p>
    <p>
      <button class="btn btn-lg btn-primary" v-on:click="$emit('onIntroNext')">Start &raquo;</button>
    </p>
  </div>
</template>

<script>
export default {
  name: 'Intro',
  props: {
    progress: {}
  },
}
</script>

// src/components/intro.jsx
import React from 'react';

const Intro = (props) => {
  return (
    <div className="jumbotron">
      <h1>Minus Level {props.shared.level.id}</h1>
      <p>{props.shared.level.desc}</p>
      <p>
        <button className="btn btn-lg btn-primary" onClick={props.onStart}>Start &raquo;</button>
      </p>
    </div>

  );
}

export default Intro;
