// src/components/problem.jsx
import React, { useState, useEffect, useCallback } from 'react';
import problemGenerator from './problem_generator.js';
import soundClick from './click.mp3';
import soundBounce from './bounce.mp3';

const Problem = (props) => {
    const [problem, setProblem] = useState({question: "", answer:0});
    const [input, setInput] = useState("");
    const audioClick = new Audio(soundClick);
    const audioBounce = new Audio(soundBounce);

    const generator = useCallback(() => {
        let func = problemGenerator["g" + props.shared.level.id];
        if(typeof func === "function")
            return func();
        else
            throw new Error("Cannot find problem_generator: " + props.shared.level.id);
    }, [props.shared.level.id]);

    useEffect(() => {
        var q;
        do {
            q = generator();
        } while (problem.question === q.question);

        setProblem(q);
        setInput("");
    }, [props.shared.right, props.shared.wrong, generator]);

    const handleSubmit = (event) => {
        event.preventDefault();

        if (Number(input) === problem.answer) {
            audioBounce.play();
            props.onAnswer(true);
        } else {
            audioClick.play();
            var wrong = problem.question + " = " + input;
            props.onAnswer(false, wrong);
            console.log(wrong);
        }
        return false;
    }

    return (
        <div className="jumbotron">
            <form onSubmit={handleSubmit}>
                <div className="input-group input-group-lg">
                    <div className="input-group-prepend">
                        <span className="input-group-text">{problem.question} = </span>
                    </div>
                    <input type="number" className="form-control" placeholder="Answer here" value={input} onChange={e => setInput(e.target.value)} autoFocus required />
                </div>
            </form>
        </div>
    );
}


export default Problem;

// src/components/Problem.vue
<template>
  <div class="jumbotron">
    <form v-on:submit.prevent="onSubmit">
      <div class="input-group input-group-lg">
        <div class="input-group-prepend">
          <span class="input-group-text">{{ question }} = </span>
        </div>
        <input v-model="inputAnswer" type="number" class="form-control" placeholder="Answer here" ref="inputAnswer">
      </div>
    </form> 
  </div>
</template>

<script>
export default {
  name: 'Problem',
  props: {
    progress: {},
  },
  data() {
    return {
      question: "",
      answer: 0,
      inputAnswer: null,
      gBounce: new Audio("assets/bounce.mp3"),
      gClick: new Audio("assets/click.mp3"),
    }
  },
  methods: {
    generateQuestion(){
    },
    onSubmit(){
      if(this.inputAnswer == "")
        return false;
        
      if(this.inputAnswer == this.answer){
          this.progress.right++;
          this.gBounce.play();
      }else{
          this.progress.wrong++;
          this.gClick.play();
          var wrong = this.question + " = " + this.inputAnswer;
          console.log(wrong);
          this.progress.wrong_questions.push(wrong);
      }

      if(this.progress.right + this.progress.wrong < this.progress.total){
        var q;
        do{
          q = this.generateQuestion()
        }while(this.question == q.question);
        
        this.question = q.question;
        this.answer = q.answer;
      }else{
         this.$emit('onProblemNext');
      }
      this.inputAnswer = "";
      return false;
    },
  },
  mounted(){
    var q = this.generateQuestion();
    this.question = q.question;
    this.answer = q.answer;
    this.$refs.inputAnswer.focus();
    this.inputAnswer="";
  }
}
</script>
